name: Buildroot-AutoBuild

on:
#  release:
#    types: [published]
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - 'start'
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  #schedule:
  #  - cron: 0 18 * * *
  #watch:
  #  types: [started]

env:
  RUN_VALIDATION: true

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    name: Build ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [generic_x86_64]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Initialization environment
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/share/

    - name: Clone source code  
      run: |
        df -hT $PWD
        git clone git://git.buildroot.net/buildroot
    
    - name: Change Settings.
      run: |
        cd buildroot
        touch generic_x86_64.config
        echo "BR2_HAVE_DOT_CONFIG=y
        BR2_HOST_GCC_AT_LEAST_4_9=y
        BR2_HOST_GCC_AT_LEAST_5=y
        BR2_HOST_GCC_AT_LEAST_6=y
        BR2_HOST_GCC_AT_LEAST_7=y
        BR2_HOST_GCC_AT_LEAST_8=y
        BR2_HOST_GCC_AT_LEAST_9=y
        BR2_ARCH_IS_64=y
        BR2_ARCH_HAS_MMU_MANDATORY=y
        BR2_x86_64=y
        BR2_ARCH_HAS_TOOLCHAIN_BUILDROOT=y
        BR2_ARCH=\"x86_64\"
        BR2_NORMALIZED_ARCH=\"x86_64\"
        BR2_ENDIAN=\"LITTLE\"
        BR2_GCC_TARGET_ARCH=\"x86-64\"
        BR2_BINFMT_SUPPORTS_SHARED=y
        BR2_READELF_ARCH_NAME=\"Advanced Micro Devices X86-64\"
        BR2_BINFMT_ELF=y
        BR2_X86_CPU_HAS_MMX=y
        BR2_X86_CPU_HAS_SSE=y
        BR2_X86_CPU_HAS_SSE2=y
        BR2_x86_x86_64=y
        BR2_WGET=\"wget --passive-ftp -nd -t 3\"
        BR2_SVN=\"svn --non-interactive\"
        BR2_BZR=\"bzr\"
        BR2_GIT=\"git\"
        BR2_CVS=\"cvs\"
        BR2_LOCALFILES=\"cp\"
        BR2_SCP=\"scp\"
        BR2_SFTP=\"sftp\"
        BR2_HG=\"hg\"
        BR2_ZCAT=\"gzip -d -c\"
        BR2_BZCAT=\"bzcat\"
        BR2_XZCAT=\"xzcat\"
        BR2_LZCAT=\"lzip -d -c\"
        BR2_TAR_OPTIONS=\"\"
        BR2_DEFCONFIG=\"$(CONFIG_DIR)/defconfig\"
        BR2_DL_DIR=\"$(TOPDIR)/dl\"
        BR2_HOST_DIR=\"$(BASE_DIR)/host\"
        BR2_PRIMARY_SITE=\"\"
        BR2_BACKUP_SITE=\"http://sources.buildroot.net\"
        BR2_KERNEL_MIRROR=\"https://cdn.kernel.org/pub\"
        BR2_GNU_MIRROR=\"http://ftpmirror.gnu.org\"
        BR2_LUAROCKS_MIRROR=\"http://rocks.moonscript.org\"
        BR2_CPAN_MIRROR=\"https://cpan.metacpan.org\"
        BR2_JLEVEL=0
        BR2_STRIP_strip=y
        BR2_STRIP_EXCLUDE_FILES=\"\"
        BR2_STRIP_EXCLUDE_DIRS=\"\"
        BR2_OPTIMIZE_S=y
        BR2_SHARED_LIBS=y
        BR2_PACKAGE_OVERRIDE_FILE=\"$(CONFIG_DIR)/local.mk\"
        BR2_GLOBAL_PATCH_DIR=\"\"
        BR2_COMPILER_PARANOID_UNSAFE_PATH=y
        BR2_PIC_PIE_ARCH_SUPPORTS=y
        BR2_PIC_PIE=y
        BR2_RELRO_FULL=y
        BR2_FORTIFY_SOURCE_ARCH_SUPPORTS=y
        BR2_TOOLCHAIN=y
        BR2_TOOLCHAIN_USES_UCLIBC=y
        BR2_TOOLCHAIN_EXTERNAL=y
        BR2_TOOLCHAIN_EXTERNAL_CUSTOM=y
        BR2_TOOLCHAIN_EXTERNAL_PREINSTALLED=y
        BR2_TOOLCHAIN_EXTERNAL_PATH=\"\"
        BR2_TOOLCHAIN_EXTERNAL_UCLIBC=y
        BR2_PACKAGE_HAS_TOOLCHAIN_EXTERNAL=y
        BR2_PACKAGE_PROVIDES_TOOLCHAIN_EXTERNAL=\"toolchain-external-custom\"
        BR2_TOOLCHAIN_EXTERNAL_PREFIX=\"$(ARCH)-linux\"
        BR2_TOOLCHAIN_EXTERNAL_BOOTLIN_ARCH_SUPPORTS=y
        BR2_TOOLCHAIN_EXTERNAL_CUSTOM_PREFIX=\"$(ARCH)-linux\"
        BR2_TOOLCHAIN_EXTERNAL_GCC_11=y
        BR2_TOOLCHAIN_EXTERNAL_HEADERS_REALLY_OLD=y
        BR2_TOOLCHAIN_EXTERNAL_CUSTOM_UCLIBC=y
        BR2_TOOLCHAIN_EXTERNAL_WCHAR=y
        BR2_TOOLCHAIN_EXTERNAL_LOCALE=y
        BR2_TOOLCHAIN_EXTERNAL_HAS_THREADS=y
        BR2_TOOLCHAIN_EXTERNAL_HAS_THREADS_DEBUG=y
        BR2_TOOLCHAIN_EXTERNAL_HAS_THREADS_NPTL=y
        BR2_TOOLCHAIN_EXTERNAL_CXX=y
        BR2_PACKAGE_HOST_GDB_ARCH_SUPPORTS=y
        BR2_TOOLCHAIN_SUPPORTS_ALWAYS_LOCKFREE_ATOMIC_INTS=y
        BR2_TOOLCHAIN_SUPPORTS_VARIADIC_MI_THUNK=y
        BR2_USE_WCHAR=y
        BR2_ENABLE_LOCALE=y
        BR2_INSTALL_LIBSTDCPP=y
        BR2_TOOLCHAIN_HAS_THREADS=y
        BR2_TOOLCHAIN_HAS_THREADS_DEBUG=y
        BR2_TOOLCHAIN_HAS_THREADS_NPTL=y
        BR2_TOOLCHAIN_HAS_UCONTEXT=y
        BR2_TOOLCHAIN_SUPPORTS_PIE=y
        BR2_TOOLCHAIN_EXTRA_LIBS=\"\"
        BR2_USE_MMU=y
        BR2_TARGET_OPTIMIZATION=\"\"
        BR2_TARGET_LDFLAGS=\"\"
        BR2_TOOLCHAIN_HEADERS_AT_LEAST=\"2.6\"
        BR2_TOOLCHAIN_GCC_AT_LEAST_4_3=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_4_4=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_4_5=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_4_6=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_4_7=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_4_8=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_4_9=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_5=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_6=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_7=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_8=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_9=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_10=y
        BR2_TOOLCHAIN_GCC_AT_LEAST_11=y
        BR2_TOOLCHAIN_GCC_AT_LEAST=\"11\"
        BR2_TOOLCHAIN_HAS_MNAN_OPTION=y
        BR2_TOOLCHAIN_HAS_SYNC_1=y
        BR2_TOOLCHAIN_HAS_SYNC_2=y
        BR2_TOOLCHAIN_HAS_SYNC_4=y
        BR2_TOOLCHAIN_HAS_SYNC_8=y
        BR2_TOOLCHAIN_HAS_LIBATOMIC=y
        BR2_TOOLCHAIN_HAS_ATOMIC=y
        BR2_TOOLCHAIN_HAS_LIBQUADMATH=y
        BR2_ROOTFS_SKELETON_DEFAULT=y
        BR2_TARGET_GENERIC_HOSTNAME=\"buildroot\"
        BR2_TARGET_GENERIC_ISSUE=\"Welcome to Buildroot\"
        BR2_TARGET_GENERIC_PASSWD_SHA256=y
        BR2_TARGET_GENERIC_PASSWD_METHOD=\"sha-256\"
        BR2_INIT_BUSYBOX=y
        BR2_ROOTFS_DEVICE_CREATION_DYNAMIC_DEVTMPFS=y
        BR2_ROOTFS_DEVICE_TABLE=\"system/device_table.txt\"
        BR2_TARGET_ENABLE_ROOT_LOGIN=y
        BR2_TARGET_GENERIC_ROOT_PASSWD=\"zhirui02\"
        BR2_SYSTEM_BIN_SH_BUSYBOX=y
        BR2_TARGET_GENERIC_GETTY=y
        BR2_TARGET_GENERIC_GETTY_PORT=\"console\"
        BR2_TARGET_GENERIC_GETTY_BAUDRATE_KEEP=y
        BR2_TARGET_GENERIC_GETTY_BAUDRATE=\"0\"
        BR2_TARGET_GENERIC_GETTY_TERM=\"vt100\"
        BR2_TARGET_GENERIC_GETTY_OPTIONS=\"\"
        BR2_TARGET_GENERIC_REMOUNT_ROOTFS_RW=y
        BR2_SYSTEM_DHCP=\"\"
        BR2_SYSTEM_DEFAULT_PATH=\"/bin:/sbin:/usr/bin:/usr/sbin\"
        BR2_ENABLE_LOCALE_PURGE=y
        BR2_ENABLE_LOCALE_WHITELIST=\"C en_US\"
        BR2_SYSTEM_ENABLE_NLS=y
        BR2_TARGET_TZ_INFO=y
        BR2_TARGET_TZ_ZONELIST=\"default\"
        BR2_TARGET_LOCALTIME=\"Etc/UTC\"
        BR2_ROOTFS_USERS_TABLES=\"\"
        BR2_ROOTFS_OVERLAY=\"\"
        BR2_ROOTFS_PRE_BUILD_SCRIPT=\"\"
        BR2_ROOTFS_POST_BUILD_SCRIPT=\"\"
        BR2_ROOTFS_POST_FAKEROOT_SCRIPT=\"\"
        BR2_ROOTFS_POST_IMAGE_SCRIPT=\"\"
        BR2_LINUX_KERNEL=y
        BR2_LINUX_KERNEL_LATEST_VERSION=y
        BR2_LINUX_KERNEL_VERSION=\"5.15.87\"
        BR2_LINUX_KERNEL_PATCH=\"\"
        BR2_LINUX_KERNEL_USE_DEFCONFIG=y
        BR2_LINUX_KERNEL_DEFCONFIG=\"\"
        BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES=\"\"
        BR2_LINUX_KERNEL_CUSTOM_LOGO_PATH=\"\"
        BR2_LINUX_KERNEL_BZIMAGE=y
        BR2_LINUX_KERNEL_GZIP=y
        BR2_LINUX_KERNEL_NEEDS_HOST_OPENSSL=y
        BR2_PACKAGE_BUSYBOX=y
        BR2_PACKAGE_BUSYBOX_CONFIG=\"package/busybox/busybox.config\"
        BR2_PACKAGE_BUSYBOX_CONFIG_FRAGMENT_FILES=\"\"
        BR2_PACKAGE_SKELETON=y
        BR2_PACKAGE_HAS_SKELETON=y
        BR2_PACKAGE_PROVIDES_SKELETON=\"skeleton-init-sysv\"
        BR2_PACKAGE_SKELETON_INIT_COMMON=y
        BR2_PACKAGE_SKELETON_INIT_SYSV=y
        BR2_PACKAGE_FFMPEG_ARCH_SUPPORTS=y
        BR2_PACKAGE_GSTREAMER1=y
        BR2_PACKAGE_GSTREAMER1_PARSE=y
        BR2_PACKAGE_GSTREAMER1_TRACE=y
        BR2_PACKAGE_GSTREAMER1_GST_DEBUG=y
        BR2_PACKAGE_GSTREAMER1_PLUGIN_REGISTRY=y
        BR2_PACKAGE_GSTREAMER1_INSTALL_TOOLS=y
        BR2_PACKAGE_GST1_PLUGINS_BASE=y
        BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_AUDIOCONVERT=y
        BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_PLAYBACK=y
        BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_AUDIORESAMPLE=y
        BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_TYPEFIND=y
        BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_VIDEOSCALE=y
        BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_VOLUME=y
        BR2_PACKAGE_KODI_ARCH_SUPPORTS=y
        BR2_PACKAGE_MJPEGTOOLS_SIMD_SUPPORT=y
        BR2_PACKAGE_PULSEAUDIO_HAS_ATOMIC=y
        BR2_PACKAGE_BROTLI=y
        BR2_PACKAGE_BPFTOOL_ARCH_SUPPORTS=y
        BR2_PACKAGE_DELVE_ARCH_SUPPORTS=y
        BR2_PACKAGE_GDB_ARCH_SUPPORTS=y
        BR2_PACKAGE_GOOGLE_BREAKPAD_ARCH_SUPPORTS=y
        BR2_PACKAGE_KVM_UNIT_TESTS_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBBPF_ARCH_SUPPORTS=y
        BR2_PACKAGE_LTP_TESTSUITE_ARCH_SUPPORTS=y
        BR2_PACKAGE_LTRACE_ARCH_SUPPORTS=y
        BR2_PACKAGE_OPROFILE_ARCH_SUPPORTS=y
        BR2_PACKAGE_PLY_ARCH_SUPPORTS=y
        BR2_PACKAGE_TCF_AGENT_ARCH=\"x86_64\"
        BR2_PACKAGE_TCF_AGENT_ARCH_SUPPORTS=y
        BR2_PACKAGE_TRINITY_ARCH_SUPPORTS=y
        BR2_PACKAGE_UFTRACE_ARCH_SUPPORTS=y
        BR2_PACKAGE_VALGRIND_ARCH_SUPPORTS=y
        BR2_PACKAGE_CMAKE_ARCH_SUPPORTS=y
        BR2_PACKAGE_GETTEXT=y
        BR2_PACKAGE_GETTEXT_PROVIDES_LIBINTL=y
        BR2_PACKAGE_HAS_GETTEXT=y
        BR2_PACKAGE_PROVIDES_GETTEXT=\"gettext-gnu\"
        BR2_PACKAGE_PROVIDES_HOST_GETTEXT=\"host-gettext-gnu\"
        BR2_PACKAGE_GETTEXT_GNU=y
        BR2_PACKAGE_MIDORI_ARCH_SUPPORTS=y
        BR2_PACKAGE_NETSURF_ARCH_SUPPORTS=y
        BR2_PACKAGE_QT5_JSCORE_AVAILABLE=y
        BR2_PACKAGE_QT5=y
        BR2_PACKAGE_QT5BASE=y
        BR2_PACKAGE_QT5BASE_CUSTOM_CONF_OPTS=\"\"
        BR2_PACKAGE_QT5BASE_CONFIG_FILE=\"\"
        BR2_PACKAGE_QT5BASE_NETWORK=y
        BR2_PACKAGE_QT5BASE_SQL=y
        BR2_PACKAGE_QT5BASE_SQLITE_NONE=y
        BR2_PACKAGE_QT5BASE_TEST=y
        BR2_PACKAGE_QT5BASE_XML=y
        BR2_PACKAGE_QT5BASE_GUI=y
        BR2_PACKAGE_QT5BASE_WIDGETS=y
        BR2_PACKAGE_QT5BASE_LINUXFB=y
        BR2_PACKAGE_QT5BASE_DEFAULT_QPA=\"\"
        BR2_PACKAGE_QT5BASE_PRINTSUPPORT=y
        BR2_PACKAGE_QT5BASE_ICU=y
        BR2_PACKAGE_QT5LOCATION=y
        BR2_PACKAGE_QT5SENSORS=y
        BR2_PACKAGE_QT5WEBCHANNEL=y
        BR2_PACKAGE_QT5WEBKIT=y
        BR2_PACKAGE_QT5WEBENGINE_ARCH_SUPPORTS=y
        BR2_PACKAGE_QT5WEBSOCKETS=y
        BR2_PACKAGE_FLASHROM_ARCH_SUPPORTS=y
        BR2_PACKAGE_SEDUTIL_ARCH_SUPPORTS=y
        BR2_PACKAGE_HOST_ERLANG_ARCH_SUPPORTS=y
        BR2_PACKAGE_ERLANG_ARCH_SUPPORTS=y
        BR2_PACKAGE_GAUCHE_ARCH_SUPPORTS=y
        BR2_PACKAGE_PROVIDES_HOST_LUAINTERPRETER=\"host-lua\"
        BR2_PACKAGE_LUAJIT_ARCH_SUPPORTS=y
        BR2_PACKAGE_HOST_MONO_ARCH_SUPPORTS=y
        BR2_PACKAGE_MONO_ARCH_SUPPORTS=y
        BR2_PACKAGE_NODEJS_ARCH_SUPPORTS=y
        BR2_PACKAGE_HOST_OPENJDK_BIN_ARCH_SUPPORTS=y
        BR2_PACKAGE_OPENJDK_ARCH_SUPPORTS=y
        BR2_PACKAGE_FDK_AAC_ARCH_SUPPORTS=y
        BR2_PACKAGE_OPENAL_ARCH_SUPPORTS=y
        BR2_PACKAGE_WEBRTC_AUDIO_PROCESSING_ARCH_SUPPORTS=y
        BR2_PACKAGE_ZLIB_NG_ARCH_SUPPORTS=y
        BR2_PACKAGE_ZLIB=y
        BR2_PACKAGE_LIBZLIB=y
        BR2_PACKAGE_HAS_ZLIB=y
        BR2_PACKAGE_PROVIDES_ZLIB=\"libzlib\"
        BR2_PACKAGE_PROVIDES_HOST_ZLIB=\"host-libzlib\"
        BR2_PACKAGE_BOTAN_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBGPG_ERROR_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBGPG_ERROR_SYSCFG=\"x86_64-unknown-linux-gnu\"
        BR2_PACKAGE_OPENSSL=y
        BR2_PACKAGE_LIBOPENSSL=y
        BR2_PACKAGE_LIBOPENSSL_TARGET_ARCH=\"linux-x86_64\"
        BR2_PACKAGE_LIBOPENSSL_ENABLE_CHACHA=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_RC2=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_RC4=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_MD2=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_MD4=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_MDC2=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_BLAKE2=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_IDEA=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_SEED=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_DES=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_RMD160=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_WHIRLPOOL=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_BLOWFISH=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_SSL=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_SSL2=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_SSL3=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_WEAK_SSL=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_PSK=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_CAST=y
        BR2_PACKAGE_LIBOPENSSL_UNSECURE=y
        BR2_PACKAGE_LIBOPENSSL_DYNAMIC_ENGINE=y
        BR2_PACKAGE_LIBOPENSSL_ENABLE_COMP=y
        BR2_PACKAGE_HAS_OPENSSL=y
        BR2_PACKAGE_PROVIDES_OPENSSL=\"libopenssl\"
        BR2_PACKAGE_PROVIDES_HOST_OPENSSL=\"host-libopenssl\"
        BR2_PACKAGE_LEVELDB=y
        BR2_PACKAGE_MONGODB_ARCH_SUPPORTS=y
        BR2_PACKAGE_ROCKSDB_ARCH_SUPPORTS=y
        BR2_PACKAGE_SQLITE=y
        BR2_PACKAGE_FREETYPE=y
        BR2_PACKAGE_JPEG_SIMD_SUPPORT=y
        BR2_PACKAGE_JPEG=y
        BR2_PACKAGE_JPEG_TURBO=y
        BR2_PACKAGE_HAS_JPEG=y
        BR2_PACKAGE_PROVIDES_JPEG=\"jpeg-turbo\"
        BR2_PACKAGE_LIBPNG=y
        BR2_PACKAGE_WEBKITGTK_ARCH_SUPPORTS=y
        BR2_PACKAGE_WEBP=y
        BR2_PACKAGE_WEBP_DEMUX=y
        BR2_PACKAGE_WOFF2=y
        BR2_PACKAGE_WPEWEBKIT_ARCH_SUPPORTS=y
        BR2_PACKAGE_GNU_EFI_ARCH_SUPPORTS=y
        BR2_PACKAGE_MRAA_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBXML2=y
        BR2_PACKAGE_LIBXSLT=y
        BR2_PACKAGE_LIBCAMERA_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBOPENH264_ARCH_SUPPORTS=y
        BR2_PACKAGE_GOBJECT_INTROSPECTION_ARCH_SUPPORTS=y
        BR2_PACKAGE_JEMALLOC_ARCH_SUPPORTS=y
        BR2_PACKAGE_LAPACK_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBABSEIL_CPP_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBATOMIC_OPS_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBBSD_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBEASTL_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBEXECINFO=y
        BR2_PACKAGE_LIBFFI=y
        BR2_PACKAGE_LIBGLIB2=y
        BR2_PACKAGE_LIBNSPR_ARCH_SUPPORT=y
        BR2_PACKAGE_LIBSECCOMP_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBSIGSEGV_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBUNWIND_ARCH_SUPPORTS=y
        BR2_PACKAGE_LIBURCU_ARCH_SUPPORTS=y
        BR2_PACKAGE_LLVM_ARCH_SUPPORTS=y
        BR2_PACKAGE_LLVM_TARGET_ARCH=\"X86\"
        BR2_PACKAGE_POCO_ARCH_SUPPORTS=y
        BR2_PACKAGE_PROTOBUF_ARCH_SUPPORTS=y
        BR2_PACKAGE_TZ=y
        BR2_PACKAGE_ICU=y
        BR2_PACKAGE_ICU_CUSTOM_DATA_PATH=\"\"
        BR2_PACKAGE_PCRE=y
        BR2_PACKAGE_PCRE_UTF=y
        BR2_PACKAGE_PCRE_UCP=y
        BR2_PACKAGE_PCRE2=y
        BR2_PACKAGE_PCRE2_16=y
        BR2_PACKAGE_PCRE2_JIT_ARCH_SUPPORTS=y
        BR2_PACKAGE_BITCOIN_ARCH_SUPPORTS=y
        BR2_PACKAGE_QEMU_ARCH_SUPPORTS_TARGET=y
        BR2_PACKAGE_HAPROXY_ARCH_SUPPORTS=y
        BR2_PACKAGE_IFUPDOWN_SCRIPTS=y
        BR2_PACKAGE_MONGREL2_LIBC_SUPPORTS=y
        BR2_PACKAGE_XENOMAI_COBALT_ARCH_SUPPORTS=y
        BR2_PACKAGE_URANDOM_SCRIPTS=y
        BR2_PACKAGE_AUDIT_ARCH_SUPPORTS=y
        BR2_PACKAGE_EFIVAR_ARCH_SUPPORTS=y
        BR2_PACKAGE_INITSCRIPTS=y
        BR2_PACKAGE_LIBVIRT_ARCH_SUPPORTS=y
        BR2_PACKAGE_MAKEDUMPFILE_ARCH_SUPPORTS=y
        BR2_PACKAGE_OPENVMTOOLS_ARCH_SUPPORTS=y
        BR2_PACKAGE_SYSTEMD_ARCH_SUPPORTS=y
        BR2_PACKAGE_SYSTEMD_BOOTCHART_ARCH_SUPPORTS=y
        BR2_PACKAGE_XVISOR_ARCH_SUPPORTS=y
        BR2_TARGET_ROOTFS_EXT2=y
        BR2_TARGET_ROOTFS_EXT2_2=y
        BR2_TARGET_ROOTFS_EXT2_2r1=y
        BR2_TARGET_ROOTFS_EXT2_GEN=2
        BR2_TARGET_ROOTFS_EXT2_REV=1
        BR2_TARGET_ROOTFS_EXT2_LABEL=\"rootfs\"
        BR2_TARGET_ROOTFS_EXT2_SIZE=\"256M\"
        BR2_TARGET_ROOTFS_EXT2_INODES=0
        BR2_TARGET_ROOTFS_EXT2_RESBLKS=5
        BR2_TARGET_ROOTFS_EXT2_MKFS_OPTIONS=\"-O ^64bit\"
        BR2_TARGET_ROOTFS_EXT2_NONE=y
        BR2_TARGET_ROOTFS_TAR=y
        BR2_TARGET_ROOTFS_TAR_NONE=y
        BR2_TARGET_ROOTFS_TAR_OPTIONS=\"\"
        BR2_TARGET_EDK2_ARCH_SUPPORTS=y
        BR2_TARGET_GRUB2_ARCH_SUPPORTS=y
        BR2_PACKAGE_SHIM_ARCH_SUPPORTS=y
        BR2_TARGET_UBOOT=y
        BR2_TARGET_UBOOT_BUILD_SYSTEM_KCONFIG=y
        BR2_TARGET_UBOOT_LATEST_VERSION=y
        BR2_TARGET_UBOOT_VERSION=\"2022.01\"
        BR2_TARGET_UBOOT_PATCH=\"\"
        BR2_TARGET_UBOOT_USE_DEFCONFIG=y
        BR2_TARGET_UBOOT_BOARD_DEFCONFIG=\"\"
        BR2_TARGET_UBOOT_CONFIG_FRAGMENT_FILES=\"\"
        BR2_TARGET_UBOOT_FORMAT_BIN=y
        BR2_TARGET_UBOOT_CUSTOM_DTS_PATH=\"\"
        BR2_TARGET_UBOOT_CUSTOM_MAKEOPTS=\"\"
        BR2_PACKAGE_HOST_E2FSPROGS=y
        BR2_PACKAGE_HOST_GO_TARGET_ARCH_SUPPORTS=y
        BR2_PACKAGE_HOST_GO_TARGET_CGO_LINKING_SUPPORTS=y
        BR2_PACKAGE_HOST_GO_HOST_ARCH_SUPPORTS=y
        BR2_PACKAGE_HOST_GO_BOOTSTRAP_ARCH_SUPPORTS=y
        BR2_PACKAGE_HOST_GOOGLE_BREAKPAD_ARCH_SUPPORTS=y
        BR2_PACKAGE_HOST_KMOD=y
        BR2_PACKAGE_HOST_MKPASSWD=y
        BR2_PACKAGE_HOST_PATCHELF=y
        BR2_PACKAGE_HOST_QEMU_ARCH_SUPPORTS=y
        BR2_PACKAGE_HOST_QEMU_SYSTEM_ARCH_SUPPORTS=y
        BR2_PACKAGE_HOST_QEMU_USER_ARCH_SUPPORTS=y
        BR2_PACKAGE_HOST_RUSTC_ARCH_SUPPORTS=y
        BR2_PACKAGE_HOST_RUSTC_ARCH=\"x86_64\"
        BR2_PACKAGE_PROVIDES_HOST_RUSTC=\"host-rust-bin\"
        BR2_PACKAGE_HOST_UTIL_LINUX=y
        BR2_TARGET_ROOTFS_OCI_ENTRYPOINT_ARGS=\"\"
        BR2_TARGET_GRUB2_BUILTIN_MODULES=\"\"
        BR2_TARGET_GRUB2_BUILTIN_CONFIG=\"\"
        BR2_PACKAGE_REFPOLICY_POLICY_VERSION=\"\"
        BR2_TOOLCHAIN_EXTRA_EXTERNAL_LIBS=\"\"
        BR2_XTENSA_OVERLAY_DIR=\"\"
        BR2_XTENSA_CUSTOM_NAME=\"\"
        BR2_TARGET_ROOTFS_EXT2_BLOCKS=0
        BR2_TARGET_ROOTFS_EXT2_EXTRA_INODES=0
        BR2_TARGET_ROOTFS_EXT2_EXTRA_BLOCKS=0
        BR2_TARGET_UBOOT_CUSTOM_PATCH_DIR=\"\"" >> generic_x86_64.config
        cat generic_x86_64.config
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: Build
      shell: 'script -q -e -c "bash {0}"'
      id: build
      run: |
        sleep $((RANDOM % 60))    
        cd buildroot
        make
    - name: Upload Firmware
      uses: actions/upload-artifact@main
      with:
        name: ${{matrix.target}}_Firmware
        path: buildroot/release
    
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
